### ISSUE TITLE
Esse repo veio na hora certa!!

### ISSUE THREAD

**Issue by lucasfrosty** [filipebarcos/immigrant-newbie#1]
Tô imigrando pro Canadá (Ottawa) em Junho (tb pela Shopify), esse teu repo com ctz vai me ajudar mt.
Por mais que o pessoal tanto da Shopify quanto da AIESEC estejam me ajudando nesse processo, é sempre bom ter uma visão BR sobre o processo de imigração pra ver quais desafios eu provavelmente eu vou enfrentar por lá.

Muito bacana a idéia, se vc continuar ela eu com ctz vou estar acompanhando.
Valeu!!

**Comment by filipebarcos** [comment]
Opa @lucasfrosty se tiver algum assunto especifico que queira saber, pode deixar a sugestão e vou tentar abordar.
